apiVersion: batch/v1
kind: Job
metadata:
  name: add-route-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        hub.jupyter.org/network-access-proxy-api: "true" 
    spec:
      containers:
      - name: add-route-job
        image: alpine
        command:
        - sh
        - -cex
        args:
          - |
            apk update
            apk add curl

            echo 'Using token $(PROXY_TOKEN)'

            curl -X POST -H 'Authorization: token $(PROXY_TOKEN)' -H 'Content-type: application/json' http://proxy-api:8001/api/routes/pipeline -d '{"target": "http://ml-pipeline-ui.kubeflow:80"}'
            curl -X POST -H 'Authorization: token $(PROXY_TOKEN)' -H 'Content-type: application/json' http://proxy-api:8001/api/routes/minio -d '{"target": "http://minio-service.kubeflow:9000"}'
        env:
          - name: PROXY_TOKEN
            valueFrom:
               secretKeyRef:
                 key:  hub.config.ConfigurableHTTPProxy.auth_token
                 name: hub
                 optional: false
      restartPolicy: Never
