apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-notebook-pvc
spec:
  resources:
    requests:
      storage: 5G
  volumeMode: Filesystem
  storageClassName: juicefs-sc
  accessModes:
    - ReadWriteMany
